name: 'Count lines in Python files'
description: 'Counts the number of lines in all Python files in the repository'
inputs:
  directory:
    description: 'The directory to count lines in'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
