name: Python application test

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Count lines in Python files
        uses: ./.github/actions/count-lines
        with:
          directory: 'test'





